InvoiceApp/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    # ------ LOGIN, ACCOUNT, REGISTER, LOGOUT, MAIN PAGE URLS ------
    path('login/', views.login, name='login'),
    path('account/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('logged_out/', views.logged_out, name='logged_out'),
    path('main_page/', views.main_page, name='main_page'),
    # ----- CLIENT URLS -----
    path('clients/', views.clients, name='clients'),
    path('clients/add_client', views.add_client, name='add_client'),
    path('clients/edit_client/<int:pk>', views.edit_client, name='edit_client'),
    path('clients/delete/<int:pk>', views.delete_client, name='delete_client'),
    # ----- PRODUCT URLS -----
    path('products/', views.products, name='products'),
    path('products/add_product', views.add_product, name='add_product'),
    path('products/edit_product/<int:pk>', views.edit_product, name='edit_product'),
    path('products/delete/<int:pk>', views.delete_product, name='delete_product'),
    # ----- SERVICE URLS -----
    path('services/', views.services, name='services'),
    path('services/add_service', views.add_service, name='add_service'),
    path('services/edit_service/<int:pk>', views.edit_service, name='edit_service'),
    path('services/delete/<int:pk>', views.delete_service, name='delete_service'),
    # ----- INVOICE URLS -----
    path('invoices/', views.invoices, name='invoices'),
    path('invoices/create_invoice', views.create_full_invoice, name='create_invoice'),
    path('invoices/edit_invoice/<int:pk>', views.edit_invoice, name='edit_invoice'),
    path('invoices/delete/<int:pk>', views.delete_invoice, name='delete_invoice'),
    # ----- COMPANY URLS -----
    path('company/', views.company_info, name='company_info'),
    path('company/add_company_info', views.add_company_info, name='add_company_info'),
    path('company/edit_company_info/<int:pk>', views.edit_company_info, name='edit_company_info'),
    path('company/delete_company_info/<int:pk>', views.delete_company_info, name='delete_company_info'),
    path('company/ajax_delete_company/', views.ajax_delete_company, name='ajax_delete_company'),
    # ----- TEMPLATES ------
    path('invoices/view_invoice_template/<int:pk>', views.invoice_template, name='invoice_template'),
    # ----- USER: PROFILE AND INVOICES------
    path('profile/', views.profile, name='profile'),
    path('all_user_invoices/', views.all_user_invoices, name='all_user_invoices'),
    # ----- SEARCH URLS ------
    path('search/', views.search, name='search'),
    path('search_clients/', views.search_clients, name='search_clients'),
    path('search_products/', views.search_products, name='search_products'),
    path('search_services/', views.search_services, name='search_services'),
    path('search_invoices/', views.search_invoices, name='search_invoices'),
    path('search_user_invoices/', views.search_user_invoices, name='search_user_invoices'),

    # ----- CHANGE USER PASSWORD ------
    path('change-password/', views.change_password, name='change_password'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('InvoiceApp.index')),
                  path('invoices/', include('InvoiceApp.urls')),
                  path('', RedirectView.as_view(url='invoice/index', permanent=False)),

              ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

InvoiceApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone, dateformat
from datetime import datetime, date, timedelta
from django.core.validators import MinValueValidator


class Client(models.Model):
    # Basic data
    client_id = models.AutoField(primary_key=True)
    client_name = models.CharField("Kliento pavadinimas", max_length=200, blank=False, null=False)
    registration_number = models.CharField("Įmonės kodas", max_length=50, blank=True, null=True)
    vat_number = models.CharField("PVM kodas", max_length=50, blank=True, null=True)
    address = models.TextField("Adresas", max_length=200, blank=True, null=True)
    email_address = models.EmailField("El. paštas", max_length=100, blank=True, null=True)
    phone_number = models.CharField("Telefono numeris", max_length=20, blank=True, null=True)
    # Additional data
    date_created = models.DateTimeField(verbose_name="Sukurtas", blank=True, null=True, default=datetime.now)
    last_updated = models.DateTimeField(verbose_name="Redaguotas", blank=True, null=True)

    def __str__(self):
        return f"{self.client_name} " \
               # f"{self.registration_number} " \
               # f"{self.vat_number} " \
               # f"{self.address} " \
               # f"{self.email_address} " \
               # f"{self.phone_number} " \
               # f"{self.date_created} " \
               # f"{self.last_updated} "

    # Saves date_created and last_updated data in desired formatting
    # Settings.py USE_TZ = False.
    def save(self, *args, **kwargs):
        formatted_date = dateformat.format(timezone.now(), 'Y-m-d H:i')

        if self.date_created is None:
            self.date_created = formatted_date

        self.last_updated = formatted_date

        super(Client, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Client"
        verbose_name_plural = "Clients"


class Product(models.Model):
    # Basic data
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField("Prekės pavadinimas", max_length=500, blank=False, null=False)
    product_code = models.CharField("Prekės kodas", max_length=50, blank=False, null=False)
    product_description = models.TextField("Prekės aprašymas", max_length=1000, blank=True, null=True)
    product_quantity = models.FloatField("Kiekis", blank=True, null=True)
    product_price = models.FloatField("Kaina", blank=True, null=True)
    # Additional data
    date_created = models.DateTimeField(verbose_name="Sukurta", blank=True, null=True, default=datetime.now)
    last_updated = models.DateTimeField(verbose_name="Redaguota", blank=True, null=True)

    def __str__(self):
        return f"{self.product_name} " \
               f"{self.product_code} " \
               f"{self.product_description} " \
               f"{self.product_quantity} " \
               f"{self.product_price} " \
               f"{self.date_created} " \
               f"{self.last_updated}"

    def save(self, *args, **kwargs):
        formatted_date = dateformat.format(timezone.now(), 'Y-m-d H:i')

        if self.date_created is None:
            self.date_created = formatted_date

        self.last_updated = formatted_date

        super(Product, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"


class Service(models.Model):
    # Basic data
    service_id = models.AutoField(primary_key=True)
    service_name = models.CharField("Paslaugos pavadinimas", max_length=500, blank=False, null=False)
    service_code = models.CharField("Paslaugos kodas", max_length=50, blank=False, null=False)
    service_description = models.TextField("Paslaugos aprašymas", max_length=1000, blank=True, null=True)
    service_quantity = models.FloatField("Kiekis", blank=True, null=True)
    service_price = models.FloatField("Kaina", blank=True, null=True)
    # Additional data
    date_created = models.DateTimeField(verbose_name="Sukurtas", blank=True, null=True, default=datetime.now)
    last_updated = models.DateTimeField(verbose_name="Redaguotas", blank=True, null=True)

    def __str__(self):
        return f"{self.service_name} " \
               f"{self.service_code} " \
               f"{self.service_description} " \
               f"{self.service_quantity} " \
               f"{self.service_price} " \
               f"{self.date_created} " \
               f"{self.last_updated}"

    def save(self, *args, **kwargs):
        formatted_date = dateformat.format(timezone.now(), 'Y-m-d H:i')

        if self.date_created is None:
            self.date_created = formatted_date

        self.last_updated = formatted_date

        super(Service, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Service"
        verbose_name_plural = "Services"


class Invoice(models.Model):
    # Basic data
    invoice_id = models.AutoField(primary_key=True)
    invoice_name = models.CharField("Serija", max_length=200, blank=True, null=True, default='INV')

    def increment_invoice_number(self):
        # if number would be changed manually, 'invoice_id' has to be replaced by order_by('invoice_number')
        last_invoice = Invoice.objects.all().order_by('invoice_id').last()
        if not last_invoice:
            return '00001'
        invoice_no = last_invoice.invoice_number
        invoice_int = int(invoice_no)
        width = 5
        new_invoice_int = invoice_int + 1
        formatted = (width - len(str(new_invoice_int))) * "0" + str(new_invoice_int)
        new_invoice_number = formatted
        return new_invoice_number

    invoice_number = models.CharField("Sąskaitos numeris", default=increment_invoice_number, max_length=10, blank=True,
                                      null=True)

    due_date = models.DateField(verbose_name="Apmokėti iki", blank=True, null=True)
    TERMS_OF_PAYMENT = [
        ('1', '1 diena'),
        ('3', '3 dienos'),
        ('5', '5 dienos'),
        ('7', '7 dienos'),
        ('14', '14 dienų'),
        ('30', '30 dienų'),
        ('60', '60 dienų'),
    ]
    payment_terms = models.CharField(verbose_name="Apmokėjimo terminas", max_length=10, blank=True, null=True,
                                     choices=TERMS_OF_PAYMENT, default='30')
    STATUS_OF_INVOICE = [
        ('l', 'Laukiama apmokėjimo'),
        ('a', 'Apmokėta'),
        ('p', 'Pradelsta'),
    ]
    invoice_status = models.CharField(verbose_name="Statusas", max_length=20, blank=True, null=True,
                                      choices=STATUS_OF_INVOICE, default='l')
    invoice_total = models.FloatField(verbose_name="Sąskaitos suma", validators=[MinValueValidator(0.0)])
    invoice_products_services = models.TextField(verbose_name="Sąskaitos prekės/paslaugos")
    # Related data
    client = models.ForeignKey(Client, verbose_name="Klientas", on_delete=models.SET_NULL, blank=False, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    # Additional data
    date_created = models.DateTimeField(verbose_name="Sukurta", blank=True, null=True, default=datetime.now)
    last_updated = models.DateTimeField(verbose_name="Redaguota", blank=True, null=True)

    def __str__(self):
        return f"{self.invoice_number} {self.invoice_name} {self.due_date} {self.date_created} {self.invoice_status} "

    def save(self, *args, **kwargs):
        formatted_date = dateformat.format(timezone.now(), 'Y-m-d H:i')

        if self.date_created is None:
            self.date_created = formatted_date
        self.last_updated = formatted_date
        self.due_date = formatted_date
        self.due_date = self.recalculate_due_back()

        super(Invoice, self).save(*args, **kwargs)

    def recalculate_due_back(self):
        value = int(self.payment_terms)
        result = date.today() + timedelta(days=value)
        return result

    class Meta:
        verbose_name = "Invoice"
        verbose_name_plural = "Invoices"


class CompanyInfo(models.Model):
    company_id = models.AutoField(primary_key=True)
    company_name = models.CharField("Įmonės pavadinimas", max_length=200)
    company_registration_number = models.CharField("Įmonės kodas", max_length=200)
    company_vat_number = models.CharField("PVM kodas", max_length=200)
    company_address = models.CharField("Adresas", max_length=200)
    company_email_address = models.EmailField("El. paštas", max_length=100)
    company_phone_number = models.CharField("Telefono numeris", max_length=20)

    def __str__(self):
        return f"{self.company_name} " \
               f"{self.company_registration_number} " \
               f"{self.company_vat_number} " \
               f"{self.company_address} " \
               f"{self.company_email_address} " \
               f"{self.company_phone_number}"

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    responsibilities = models.CharField("Pareigos", max_length=200)
    phone_number = models.CharField("Telefono numeris", max_length=200)

    def __str__(self):
        return f"{self.user.username}, {self.responsibilities}"

InvoiceApp/templates/search/search_base.html
{% if user.is_authenticated %}
    <body>
        {% if searched %}
            <h1>Paieškos pagal "{{ searched }}" rezultatai:</h1>
            <br>
            {% if clients %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Kliento pavadinimas</th>
                                <th scope="col">Įmonės kodas</th>
                                <th scope="col">PVM kodas</th>
                                <th scope="col">Adresas</th>
                                <th scope="col">El. paštas</th>
                                <th scope="col">Telefono numeris</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for client in clients %}
                        <tr>
                            <td>{{ client.client_name }}</td>
                            <td>{{ client.registration_number }}</td>
                            <td>{{ client.vat_number }}</td>
                            <td>{{ client.address }}</td>
                            <td>{{ client.email_address }}</td>
                            <td>{{ client.phone_number }}</td>
                            <td>
                                <a href="{% url 'edit_client' client.client_id %}" class="btn btn-warning">Redaguoti</a>
                            </td>
                            <td>
                                <a href="{% url 'delete_client' client.client_id %}" class="btn btn-danger">Trinti</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% elif products %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Prekės pavadinimas</th>
                                <th scope="col">Prekės kodas</th>
                                <th scope="col">Prekės aprašymas</th>
                                <th scope="col">Kiekis</th>
                                <th scope="col">Kaina</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for product in products %}
                        <tr>
                            <td>{{ product.product_name }}</td>
                            <td>{{ product.product_code }}</td>
                            <td>{{ product.product_description|default:'Nenurodyta' }}</td>
                            <td>{{ product.product_quantity|default:'Nenurodyta' }}</td>
                            <td>{{ product.product_price|default:'Nenurodyta'|floatformat:2 }}</td>
                            <td>
                                <a href="{% url 'edit_product' product.product_id %}" class="btn btn-warning">Redaguoti</a>
                            </td>
                            <td>
                                <a href="{% url 'delete_product' product.product_id %}" class="btn btn-danger">Trinti</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% elif services %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Paslaugos pavadinimas</th>
                                <th scope="col">Paslaugos kodas</th>
                                <th scope="col">Paslaugos aprašymas</th>
                                <th scope="col">Kiekis</th>
                                <th scope="col">Kaina</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for service in services %}
                        <tr>
                            <td>{{ service.service_name }}</td>
                            <td>{{ service.service_code }}</td>
                            <td>{{ service.service_description|default:'Nenurodyta' }}</td>
                            <td>{{ service.service_quantity|default:'Nenurodyta' }}</td>
                            <td>{{ service.service_price|default:'Nenurodyta'|floatformat:2 }}</td>
                            <td>
                                <a href="{% url 'edit_service' service.service_id %}" class="btn btn-warning">Redaguoti</a>
                            </td>
                            <td>
                                <a href="{% url 'delete_service' service.service_id %}" class="btn btn-danger">Trinti</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% elif invoices %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Sąskaitos numeris</th>
                                <th scope="col">Gavėjas</th>
                                <th scope="col">Išrašymo data</th>
                                <th scope="col">Apmokėti iki</th>
                                <th scope="col">Statusas</th>
                                <th scope="col">Sąskaitos suma</th>
                                <th scope="col">Sąskaitą išrašė</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for invoice in invoices %}
                        <tr>
                            <td>{{ invoice.invoice_number }}</td>
                            <td>{{ invoice.client.client_name }}</td>
                            <td>{{ invoice.date_created|date:"Y-m-d H:i" }}</td>
                            <td>{{ invoice.due_date|date:"Y-m-d"}}</td>
                            <td>{{ invoice.get_invoice_status_display }}</td>
                            <td>{{ invoice.invoice_total|floatformat:2 }}€</td>
                            <td>{{ invoice.user.first_name }} {{ invoice.user.last_name }}</td>
                            <td>
                                <a href="{% url 'invoice_template' invoice.invoice_id %}" class="btn btn-success">Peržiūrėti</a>
                            </td>
                            <td>
                                <a href="{% url 'edit_invoice' invoice.invoice_id %}" class="btn btn-warning">Redaguoti</a>
                            </td>
                            <td>
                                <a href="{% url 'delete_invoice' invoice.invoice_id %}" class="btn btn-danger">Trinti</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>Pagal užklausą "{{ searched }}" nieko nerasta.</h1>
            {% endif %}
        {% else %}
            <h1>Kadangi nieko neįvedėte į paieškos laukelį, todėl nieko neradome...<br>Bandykite dar kartą.</h1>
        {% endif %}
    </body>
{% endif %}

InvoiceApp/templates/search/search_clients.html
{% if user.is_authenticated %}
    <body>
        {% if searched %}
            <h1>Paieškos pagal "{{ searched }}" rezultatai:</h1>
            <br>
            {% if clients %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Kliento pavadinimas</th>
                                <th scope="col">Įmonės kodas</th>
                                <th scope="col">PVM kodas</th>
                                <th scope="col">Adresas</th>
                                <th scope="col">El. paštas</th>
                                <th scope="col">Telefono numeris</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for client in clients %}
                        <tr>
                            <td>{{ client.client_name }}</td>
                            <td>{{ client.registration_number }}</td>
                            <td>{{ client.vat_number }}</td>
                            <td>{{ client.address }}</td>
                            <td>{{ client.email_address }}</td>
                            <td>{{ client.phone_number }}</td>
                            <td>
                                <a href="{% url 'edit_client' client.client_id %}" class="btn btn-warning">Redaguoti</a>
                            </td>
                            <td>
                                <a href="{% url 'delete_client' client.client_id %}" class="btn btn-danger">Trinti</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>Klientas {{ searched }} neegzistuoja.</h1>
            {% endif %}
        {% else %}
            <h1>Kadangi nieko neįvedėte į paieškos laukelį, todėl nieko neradome...<br>Bandykite dar kartą.</h1>
        {% endif %}
    </body>
{% endif %}

InvoiceApp/templates/search/search_invoices.html
{% if user.is_authenticated %}
    <body>
        {% if searched %}
            <h1>Paieškos pagal "{{ searched }}" rezultatai:</h1>
            <br>
            {% if invoices %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Sąskaitos numeris</th>
                                <th scope="col">Gavėjas</th>
                                <th scope="col">Išrašymo data</th>
                                <th scope="col">Apmokėti iki</th>
                                <th scope="col">Statusas</th>
                                <th scope="col">Sąskaitos suma</th>
                                <th scope="col">Sąskaitą išrašė</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for invoice in invoices %}
                        <tr>
                            <td>{{ invoice.invoice_number }}</td>
                            <td>{{ invoice.client.client_name }}</td>
                            <td>{{ invoice.date_created|date:"Y-m-d H:i" }}</td>
                            <td>{{ invoice.due_date|date:"Y-m-d"}}</td>
                            <td>{{ invoice.get_invoice_status_display }}</td>
                            <td>{{ invoice.invoice_total|floatformat:2 }}€</td>
                            <td>{{ invoice.user.first_name }} {{ invoice.user.last_name }}</td>
                            <td>
                                <a href="{% url 'invoice_template' invoice.invoice_id %}" class="btn btn-success">Peržiūrėti</a>
                            </td>
                            <td>
                                <a href="{% url 'edit_invoice' invoice.invoice_id %}" class="btn btn-warning">Redaguoti</a>
                            </td>
                            <td>
                                <a href="{% url 'delete_invoice' invoice.invoice_id %}" class="btn btn-danger">Trinti</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>Sąskaita "{{ searched }}" neegzistuoja.</h1>
            {% endif %}
        {% else %}
            <h1>Kadangi nieko neįvedėte į paieškos laukelį, todėl nieko neradome...<br>Bandykite dar kartą.</h1>
        {% endif %}
    </body>
{% endif %}

InvoiceApp/templates/search/search_products.html
{% if user.is_authenticated %}
    <body>
        {% if searched %}
            <h1>Paieškos pagal "{{ searched }}" rezultatai:</h1>
            <br>
            {% if products %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Prekės pavadinimas</th>
                                <th scope="col">Prekės kodas</th>
                                <th scope="col">Prekės aprašymas</th>
                                <th scope="col">Kiekis</th>
                                <th scope="col">Kaina</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                        {% for product in products %}
                        <tr>
                            <td>{{ product.product_name }}</td>
                            <td>{{ product.product_code }}</td>
                            <td>{{ product.product_description|default:'Nenurodyta' }}</td>
                            <td>{{ product.product_quantity|default:'Nenurodyta' }}</td>
                            <td>{{ product.product_price|default:'Nenurodyta'|floatformat:2 }}</td>
                            <td>
                                <a href="{% url 'edit_product' product.product_id %}" class="btn btn-warning">Redaguoti</a>
                            </td>
                            <td>
                                <a href="{% url 'delete_product' product.product_id %}" class="btn btn-danger">Trinti</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>Prekė "{{ searched }}" neegzistuoja.</h1>
            {% endif %}
        {% else %}
            <h1>Kadangi nieko neįvedėte į paieškos laukelį, todėl nieko neradome...<br>Bandykite dar kartą.</h1>
        {% endif %}
    </body>
{% endif %}

InvoiceApp/templates/search/search_user_invoices.html
{% if user.is_authenticated %}
    <body>
        {% if searched %}
            <h1>Paieškos pagal "{{ searched }}" rezultatai:</h1>
            <br>
            {% if user_invoices %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Sąskaitos numeris</th>
                                <th scope="col">Gavėjas</th>
                                <th scope="col">Išrašymo data</th>
                                <th scope="col">Apmokėti iki</th>
                                <th scope="col">Statusas</th>
                                <th scope="col">Sąskaitos suma</th>
                                <th scope="col">Sąskaitą išrašė</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for invoice in user_invoices %}
                            <tr>
                                <td>{{ invoice.invoice_number }}</td>
                                <td>{{ invoice.client.client_name }}</td>
                                <td>{{ invoice.date_created|date:"Y-m-d H:i" }}</td>
                                <td>{{ invoice.due_date|date:"Y-m-d" }}</td>
                                <td>{{ invoice.get_invoice_status_display }}</td>
                                <td>{{ invoice.invoice_total|floatformat:2 }}€</td>
                                <td>{{ invoice.user.first_name }} {{ invoice.user.last_name }}</td>
                                <td>
                                    <a href="{% url 'invoice_template' invoice.invoice_id %}" class="btn btn-success">Peržiūrėti</a>
                                </td>
                                <td>
                                    <a href="{% url 'edit_invoice' invoice.invoice_id %}" class="btn btn-warning">Redaguoti</a>
                                </td>
                                <td>
                                    <a href="{% url 'delete_invoice' invoice.invoice_id %}" class="btn btn-danger">Trinti</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>Jūs neturite prieigos prie šios sąskaitos, nes ją paruošė kitas vartotojas.</h1>
            {% endif %}
        {% else %}
            <h1>Kadangi nieko neįvedėte į paieškos laukelį, todėl nieko neradome...<br>Bandykite dar kartą.</h1>
        {% endif %}
    </body>
{% endif %}